# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c933636a86fd986d9ec4c9de9a948d966feb12cabe0c84b06b08fffc16b3fa5ecf05cd3be3e7af0ceda81504c02e4a1f15afa092cae776bb6adc35704e7490e9

test:
  secret_key_base: 6c047b5a2a91a95e1e25d2f1a0ef3e2793c58bc982a29e2343f3ef61ccda51006955aa589aa0a90dd3bf1e4efda184541fed57feb8a7f77b92c7327441db983a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
